ok:
  http:
    connect-timeout: 60
    read-timeout: 60
    write-timeout: 60
    max-idle-connections: 200
    keep-alive-duration: 300

service-key:
  privatekey: "0xeaeae0286d26c699b30a2e85d4db8c672288d35653a0c71a984b2ee4543877bf"

wallet:
  privatekey: "0x02d8e373065d355cc021d6ab465f35859a5ec68d60c0c9d10b35679f1ec391c4"

oracle:
  callBack:
    url: ""

oracle-result-task:
  switch: true
  tempo: 5000
  max-execute: 50
  interval-second: 5

vn-mapping-file-path: "D://ideaWorkspace/opendid/client-gateway/src/main/resources/init/vnmapping.yaml"